import os
from datetime import datetime
from enum import Enum
from typing import Optional, List
import asyncio
import json
import re
import google.generativeai as genai

import httpx
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
import aiofiles
from datetime import datetime
import json
import os

from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# ------------- Config -------------
# In a real scenario, use os.getenv("OPENWEATHER_API_KEY")
# For this prototype, users must set the env var or replace it here.
OPENWEATHER_API_KEY = os.getenv("OPENWEATHER_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

OPENWEATHER_BASE = "https://api.openweathermap.org"
LOG_FILE = "search_cache.json"


# ------------- Domain models -------------

class AQICategory(str, Enum):
    good = "Good"
    fair = "Fair"
    moderate = "Moderate"
    poor = "Poor"
    very_poor = "Very Poor"
    severe = "Severe"

class PollutantComponents(BaseModel):
    co: float = Field(..., description="Carbon monoxide µg/m3")
    no: float
    no2: float
    o3: float
    so2: float
    pm2_5: float
    pm10: float
    nh3: float

class AirQuality(BaseModel):
    aqi_index: int
    aqi_category: AQICategory
    components: PollutantComponents

class Weather(BaseModel):
    temperature_c: float
    humidity: int
    pressure: int
    wind_speed: float
    wind_deg: int
    clouds: int
    description: Optional[str] = ""

class FusedSensorSnapshot(BaseModel):
    lat: float
    lon: float
    timestamp_utc: datetime
    air_quality: AirQuality
    weather: Weather
    dispersion_score: float = Field(
        ..., description="Simple heuristic: higher = better dispersion"
    )
    health_risk_level: AQICategory
    agent_insight: str = Field(..., description="NLP-friendly insight generated by the agent")
    data: Optional[dict] = None


class AskResponse(BaseModel):
    answer: str
    location: Optional[dict] = None
    data: Optional[dict] = None

class PM25ForecastItem(BaseModel):
    date: str
    predicted_pm25: float



# ------------- Helper functions -------------

def calculate_sub_index(concentration: float, breakpoints: List[tuple]) -> int:
    """Calculates sub-index for a single pollutant based on breakpoints."""
    for (low_c, high_c, low_i, high_i) in breakpoints:
        if low_c <= concentration <= high_c:
            return int(low_i + (high_i - low_i) / (high_c - low_c) * (concentration - low_c))
    return 500 # Cap at 500 if exceeds

def calculate_ind_aqi(pm25: float, pm10: float) -> int:
    """Calculates Indian AQI (0-500) based on PM2.5 and PM10."""
    # Breakpoints (Conc Low, Conc High, AQI Low, AQI High)
    pm25_bp = [
        (0, 30, 0, 50), (30, 60, 51, 100), (60, 90, 101, 200),
        (90, 120, 201, 300), (120, 250, 301, 400), (250, 1000, 401, 500)
    ]
    pm10_bp = [
        (0, 50, 0, 50), (50, 100, 51, 100), (100, 250, 101, 200),
        (250, 350, 201, 300), (350, 430, 301, 400), (430, 1000, 401, 500)
    ]
    
    val25 = calculate_sub_index(pm25, pm25_bp)
    val10 = calculate_sub_index(pm10, pm10_bp)
    
    return max(val25, val10)

def aqi_to_category(aqi: int) -> AQICategory:
    # Standard AQI Scale 0-500
    if aqi <= 50: return AQICategory.good
    if aqi <= 100: return AQICategory.fair # Satisfactory
    if aqi <= 200: return AQICategory.moderate
    if aqi <= 300: return AQICategory.poor
    if aqi <= 400: return AQICategory.very_poor
    return AQICategory.severe

def generate_agent_insight(aqi_cat: AQICategory, wind_speed: float, pm25: float, pm10: float, aqi_score: int) -> str:
    """Generates a dynamic text insight based on fusion of signals."""
    insight = f"Air quality is {aqi_cat.value} (AQI: {aqi_score} | PM2.5: {pm25:.1f} | PM10: {pm10:.1f})."
    if aqi_cat in [AQICategory.poor, AQICategory.very_poor, AQICategory.severe]:
        insight += " Hazardous levels."
    elif aqi_cat == AQICategory.moderate:
        insight += " Acceptable."
    else:
        insight += " Good air."
        
    if wind_speed > 20:
        insight += " High winds active."
    elif wind_speed < 5 and pm25 > 50:
        insight += " Stagnant air."
        
    return insight

async def save_to_json_cache(data: dict, filename: str = "sensor_data_log.json"):
    """
    Appends the given data to a JSON file, ensuring it remains a valid JSON array.
    """
    try:
        # Add timestamp if missing
        if "timestamp_logged" not in data:
            data["timestamp_logged"] = datetime.now().isoformat()
        
        # Read existing file to check if it's empty or has data
        file_exists = os.path.exists(filename)
        mode = 'r+' if file_exists else 'w'
        
        if not file_exists:
            # Create new array
            async with aiofiles.open(filename, mode='w') as f:
                await f.write(json.dumps([data], indent=2))
        else:
            # Append seamlessly to the array
            # This is not efficient for massive files but fine for this demo/log size
            try:
                async with aiofiles.open(filename, mode='r') as f:
                    content = await f.read()
                    existing_data = json.loads(content) if content else []
                    if not isinstance(existing_data, list): existing_data = [existing_data]
            except Exception:
                existing_data = [] # Corrupt file reset
            
            existing_data.append(data)
            
            async with aiofiles.open(filename, mode='w') as f:
                await f.write(json.dumps(existing_data, indent=2))
                
    except Exception as e:
        print(f"Failed to log data to cache: {e}")
        import traceback
        traceback.print_exc()

async def fetch_air_quality(client: httpx.AsyncClient, lat: float, lon: float):
    key = os.getenv("OPENWEATHER_API_KEY")
    if not key:
        return {
            "aqi_index": 150,
            "components": {"co": 250, "no": 0.5, "no2": 10, "o3": 60, "so2": 15, "pm2_5": 45, "pm10": 80, "nh3": 2},
            "dt": int(datetime.utcnow().timestamp())
        }

    url = f"{OPENWEATHER_BASE}/data/2.5/air_pollution"
    params = {"lat": lat, "lon": lon, "appid": key}
    r = await client.get(url, params=params, timeout=10)
    if r.status_code != 200:
         # Fallback mock on error
        print(f"API Error: {r.text}")
        return {
            "aqi_index": 150,
            "components": {"co": 250, "no": 0.5, "no2": 10, "o3": 60, "so2": 15, "pm2_5": 45, "pm10": 80, "nh3": 2},
            "dt": int(datetime.utcnow().timestamp())
        }
    data = r.json()
    item = data["list"][0]
    comps = item["components"]
    
    # Calculate Real AQI
    real_aqi = calculate_ind_aqi(comps["pm2_5"], comps["pm10"])
    
    return {
        "aqi_index": real_aqi, # Now returns 0-500 e.g. 153
        "components": comps,
        "dt": item["dt"],
    }

async def fetch_weather(client: httpx.AsyncClient, lat: float, lon: float):
    key = os.getenv("OPENWEATHER_API_KEY")
    if not key:
        return {
            "temperature_c": 28.5, "humidity": 60, "pressure": 1013, 
            "wind_speed": 3.5, "wind_deg": 180, "clouds": 20, "dt": int(datetime.utcnow().timestamp())
        }

    url = f"{OPENWEATHER_BASE}/data/2.5/weather"
    params = {"lat": lat, "lon": lon, "appid": key, "units": "metric"}
    r = await client.get(url, params=params, timeout=10)
    if r.status_code != 200:
        return {
            "temperature_c": 28.5, "humidity": 60, "pressure": 1013, 
            "wind_speed": 3.5, "wind_deg": 180, "clouds": 20, "dt": int(datetime.utcnow().timestamp())
        }
    data = r.json()
    return {
        "temperature_c": data["main"]["temp"],
        "humidity": data["main"]["humidity"],
        "pressure": data["main"]["pressure"],
        "wind_speed": data["wind"]["speed"],
        "wind_deg": data["wind"].get("deg", 0),
        "clouds": data["clouds"]["all"],
        "dt": data["dt"],
    }

async def fetch_coordinates(client: httpx.AsyncClient, city_name: str):
    if not OPENWEATHER_API_KEY:
        # Mock coordinates
        return {"lat": 28.6139, "lon": 77.2090, "name": city_name} # Default to Delhi

    url = f"http://api.openweathermap.org/geo/1.0/direct"
    params = {"q": city_name, "limit": 1, "appid": OPENWEATHER_API_KEY}
    
    # Mock Database for Fallback
    MOCK_DB = {
        "new delhi": {"lat": 28.6139, "lon": 77.2090, "name": "New Delhi"},
        "mumbai": {"lat": 19.0760, "lon": 72.8777, "name": "Mumbai"},
        "hyderabad": {"lat": 17.3850, "lon": 78.4867, "name": "Hyderabad"},
        "bangalore": {"lat": 12.9716, "lon": 77.5946, "name": "Bangalore"},
        "chennai": {"lat": 13.0827, "lon": 80.2707, "name": "Chennai"},
        "kolkata": {"lat": 22.5726, "lon": 88.3639, "name": "Kolkata"},
        "ayodhya": {"lat": 26.7922, "lon": 82.1998, "name": "Ayodhya"},
        "paris": {"lat": 48.8566, "lon": 2.3522, "name": "Paris"},
        "london": {"lat": 51.5074, "lon": -0.1278, "name": "London"},
        "tokyo": {"lat": 35.6762, "lon": 139.6503, "name": "Tokyo"},
        "new york": {"lat": 40.7128, "lon": -74.0060, "name": "New York"},
    }
    
    try:
        r = await client.get(url, params=params, timeout=10)
        if r.status_code == 200 and r.json():
            data = r.json()[0]
            return {"lat": data["lat"], "lon": data["lon"], "name": data["name"]}
        else:
            print(f"Geocode API Error (Using Mock): {r.status_code} - {r.text}")
            raise Exception("API Error")
            
    except Exception as e:
        print(f"Geocode failed (Falling back to mock): {e}")
        key = city_name.lower()
        if key in MOCK_DB:
            return MOCK_DB[key]
        # Heuristic fallback for unknown cities to keep app running
        print(f"Unknown city '{city_name}', returning random coords near Hyderabad")
        return {"lat": 17.0 + (len(city_name)%5), "lon": 78.0 + (len(city_name)%5), "name": city_name.title()}

def compute_dispersion_score(aqi_index: int, wind_speed: float, clouds: int) -> float:
    base = max(0.0, 6 - aqi_index)
    wind_factor = min(wind_speed / 5.0, 2.0)
    cloud_factor = max(0.5, 1.5 - clouds / 100.0)
    return round(base * wind_factor * cloud_factor, 2)


# ------------- FastAPI app -------------

app = FastAPI(
    title="GeoGuardian Sensor Fusion Agent",
    description="Combines air quality and weather data into a fused environmental signal.",
    version="0.1.0",
)

# Enable CORS for frontend integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # Allow all for prototype
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/health")
async def health():
    return {"status": "ok", "mode": "mock" if not OPENWEATHER_API_KEY else "live"}

@app.get("/fusion", response_model=FusedSensorSnapshot)
async def fuse_signals(
    lat: float = Query(..., ge=-90, le=90),
    lon: float = Query(..., ge=-180, le=180),
):
    """
    Core endpoint for the Sensor Fusion Agent.
    Input: lat, lon.
    Output: fused AQ + weather with derived metrics.
    """
    async with httpx.AsyncClient() as client:
        aq_data, w_data = await asyncio.gather(
            fetch_air_quality(client, lat, lon),
            fetch_weather(client, lat, lon),
        )

    ts = max(aq_data["dt"], w_data["dt"])
    dispersion = compute_dispersion_score(
        aqi_index=aq_data["aqi_index"],
        wind_speed=w_data["wind_speed"],
        clouds=w_data["clouds"],
    )
    health_risk = aqi_to_category(aq_data["aqi_index"])
    
    # Generate Insight
    insight = generate_agent_insight(health_risk, w_data["wind_speed"], aq_data["components"]["pm2_5"], aq_data["components"]["pm10"], aq_data["aqi_index"])

    return FusedSensorSnapshot(
        lat=lat,
        lon=lon,
        timestamp_utc=datetime.fromtimestamp(ts),
        air_quality=AirQuality(
            aqi_index=aq_data["aqi_index"],
            aqi_category=health_risk,
            components=PollutantComponents(**aq_data["components"]),
        ),
        weather=Weather(**{k: v for k, v in w_data.items() if k != "dt"}),
        dispersion_score=dispersion,
        health_risk_level=health_risk,
        agent_insight=insight
    )

@app.get("/search", response_model=FusedSensorSnapshot)
async def search_city(q: str = Query(..., min_length=1)):
    """
    Search for a city, geocode it, and return fused environmental data.
    Uses JSON cache for faster retrieval.
    """
    
    # 1. Check Cache
    try:
        if os.path.exists(LOG_FILE):
             async with aiofiles.open(LOG_FILE, mode='r') as f:
                content = await f.read()
                try:
                    logs = json.loads(content)
                    # Find a valid search_result for this query or location
                    cached = next((item for item in logs if item.get("type") == "search_result" and (item.get("query", "").lower() == q.lower() or item.get("location", "").lower() == q.lower())), None)
                    
                    if cached:
                        print(f"Cache hit for {q}")
                        # Return cached data if structurally valid, else continue to fetch
                        # This is a simple cache; in prod, check timestamp for freshness
                        try:
                            return FusedSensorSnapshot(**cached["data"])
                        except:
                            pass # Invalid structure, re-fetch
                except json.JSONDecodeError:
                    pass
    except Exception as e:
        print(f"Cache check error: {e}")

    async with httpx.AsyncClient() as client:
        # 1. Geocode
        coords = await fetch_coordinates(client, q)
        lat, lon = coords["lat"], coords["lon"]
        
        # 2. Fuse Signals (Reusing logic)
        aq_data, w_data = await asyncio.gather(
            fetch_air_quality(client, lat, lon),
            fetch_weather(client, lat, lon),
        )

        # 3. Fetch AccuWeather for Forecast & RealFeel
        import accuweather_client
        accu_data = await accuweather_client.fetch_accuweather_data(client, coords["name"])

    ts = max(aq_data["dt"], w_data["dt"])
    dispersion = compute_dispersion_score(
        aqi_index=aq_data["aqi_index"],
        wind_speed=w_data["wind_speed"],
        clouds=w_data["clouds"],
    )
    health_risk = aqi_to_category(aq_data["aqi_index"])
    
    insight = generate_agent_insight(health_risk, w_data["wind_speed"], aq_data["components"]["pm2_5"], aq_data["components"]["pm10"], aq_data["aqi_index"])

    # Enhance Weather with RealFeel if available
    weather_obj = Weather(**{k: v for k, v in w_data.items() if k != "dt"})
    if accu_data and accu_data.get("current"):
        rf = accu_data["current"].get("RealFeelTemperature", {}).get("Metric", {}).get("Value")
        if rf:
            # Append RealFeel to description or similar if strictly adhering to model, 
            # or ideally add a field to Weather model. For now, we append to condition text.
            weather_obj.description += f" (RealFeel: {rf}°C)"

    # Construct Forecast
    forecast_list = []
    if accu_data and accu_data.get("forecast"):
        daily = accu_data["forecast"].get("DailyForecasts", [])
        for day in daily[:3]:
            forecast_list.append({
                "date": day["Date"],
                "min_temp": day["Temperature"]["Minimum"]["Value"],
                "max_temp": day["Temperature"]["Maximum"]["Value"], 
                "avg_temp": (day["Temperature"]["Minimum"]["Value"] + day["Temperature"]["Maximum"]["Value"]) / 2, # Approx
                "condition": day["Day"]["IconPhrase"]
            })

    result = FusedSensorSnapshot(
        lat=lat,
        lon=lon,
        timestamp_utc=datetime.fromtimestamp(ts),
        air_quality=AirQuality(
            aqi_index=aq_data["aqi_index"],
            aqi_category=health_risk,
            components=PollutantComponents(**aq_data["components"]),
        ),
        weather=weather_obj,
        dispersion_score=dispersion,
        health_risk_level=health_risk,
        agent_insight=f"Search Result for {coords['name']}: {insight}",
        data={"forecast_3day": forecast_list} # Inject forecast into generic data dict
    )

    # Log to Cache
    await save_to_json_cache({
        "type": "search_result",
        "query": q,
        "location": coords["name"],
        "data": json.loads(result.json())
    })
    
    return result

@app.get("/ask", response_model=AskResponse)
async def ask_agent(q: str = Query(..., min_length=1)):
    if not os.getenv("GROQ_API_KEY"):
        raise HTTPException(status_code=503, detail="Groq AI not configured")

    from groq import Groq
    client_groq = Groq(api_key=os.getenv("GROQ_API_KEY"))

    async with httpx.AsyncClient() as client:
        # 1. Intent Classification & Entity Extraction via Groq
        try:
             # Enhanced prompt for indirect location references
            prompt1 = f"""
            Analyze this query: "{q}"
            1. Identify if the user is asking about a location (even indirectly like "Capital of India").
            2. If yes, resolve the specific City Name.
            3. Determine the intent: "weather", "aqi", "general".
            
            Output JSON only: {{"city": "ResolvedCityName" or null, "intent": "string"}}
            """
            
            completion = client_groq.chat.completions.create(
                messages=[{"role": "user", "content": prompt1}],
                model="llama-3.3-70b-versatile",
                temperature=0,
                response_format={"type": "json_object"}
            )
            resp1_text = completion.choices[0].message.content
            print(f"Groq Intent Response: {resp1_text}")
            
        except Exception as e:
            print(f"Groq Intent/Setup Error: {e}")
            raise HTTPException(status_code=500, detail=f"AI Error: {e}")

        city = None
        intent = "general"
        try:
            parsed = json.loads(resp1_text)
            city = parsed.get("city")
            intent = parsed.get("intent", "general")
        except Exception as e:
            print(f"Failed to parse Groq intention: {resp1_text}, Error: {e}")

        data_context = {}
        location_info = None

        # 2. Fetch Data if City Found
        if city:
            try:
                coords = await fetch_coordinates(client, city)
                lat, lon = coords["lat"], coords["lon"]
                location_info = {"lat": lat, "lon": lon, "name": coords["name"]}
                
                # Fetch basic OpenWeather Data
                aq_data, w_data = await asyncio.gather(
                    fetch_air_quality(client, lat, lon),
                    fetch_weather(client, lat, lon),
                )
                
                # Fetch Detailed AccuWeather Forecast
                import accuweather_client
                accu_data = await accuweather_client.fetch_accuweather_data(client, coords["name"])
                
                # Retrieve forecast for immediate display (Today, Tomorrow, DayAfter)
                forecast_summary = []
                if accu_data and accu_data.get("forecast"):
                    daily = accu_data["forecast"].get("DailyForecasts", [])
                    for day in daily[:3]:
                        forecast_summary.append({
                            "date": day["Date"],
                            "min_temp": day["Temperature"]["Minimum"]["Value"],
                            "max_temp": day["Temperature"]["Maximum"]["Value"],
                            "unit": day["Temperature"]["Maximum"]["Unit"],
                            "phrase": day["Day"]["IconPhrase"]
                        })

                data_context = {
                    "location": coords["name"],
                    "current": {
                        "temp": w_data["temperature_c"],
                        "aqi": aq_data["aqi_index"],
                        "pm25": aq_data["components"]["pm2_5"],
                        "wind": w_data["wind_speed"],
                        "insight": generate_agent_insight(aqi_to_category(aq_data["aqi_index"]), w_data["wind_speed"], aq_data["components"]["pm2_5"], aq_data["components"]["pm10"], aq_data["aqi_index"])
                    },
                    "forecast_3day": forecast_summary
                }
            except Exception as e:
                print(f"Data fetch error: {e}")

        # 3. Generate Answer
        prompt2 = f"""
        User Query: "{q}"
        Resolved City: {city}
        Context Data: {json.dumps(data_context)}
        
        Task:
        1. Answer the user's question naturally.
        2. If data is present, explicitly mention the current AQI, Temperature, and the 3-day forecast trend.
        3. If the query was about "Capital of X", confirm the city name in the answer.
        4. Be concise and helpful.
        """
        try:
            completion2 = client_groq.chat.completions.create(
                messages=[{"role": "user", "content": prompt2}],
                model="llama-3.3-70b-versatile",
                temperature=0.5
            )
            final_answer = completion2.choices[0].message.content
        except Exception as e:
            print(f"Groq Answer Gen Error: {e}")
            final_answer = "I'm sorry, I couldn't generate a response at this time."
        
        if city:
            # Log successful ask
            await save_to_json_cache({
                "type": "ask_interaction",
                "query": q,
                "city_resolved": city,
                "intent": intent, 
                "response": final_answer
            })
            
        return AskResponse(
            answer=final_answer,
            location=location_info,
            data=data_context
        )

@app.post("/train")
async def train_model_endpoint():
    """Trigger model training on local Hyderabad data."""
    print("Training endpoint called...")
    try:
        import ml_engine
        print("Imported ml_engine, starting training...")
        result = ml_engine.train_model()
        print(f"Training result: {result}")
        return result
    except Exception as e:
        print(f"Training error: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

class NewsArticle(BaseModel):
    title: str
    url: str
    source: str
    published_at: str

@app.get("/news", response_model=dict)
async def get_city_news(city: str = Query(..., min_length=1)):
    """
    Fetches top 3 pollution-related news articles for the city.
    Uses Google News RSS (Public Feed) to avoid API keys.
    """
    import xml.etree.ElementTree as ET
    from email.utils import parsedate_to_datetime

    rss_url = f"https://news.google.com/rss/search?q={city}+air+pollution+when:7d&hl=en-US&gl=US&ceid=US:en"
    
    articles = []
    print(f"Fetching news for {city} from {rss_url}")
    
    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(rss_url, timeout=10.0)
            if response.status_code == 200:
                root = ET.fromstring(response.content)
                # Parse headlines
                count = 0
                for item in root.findall(".//item"):
                    if count >= 3: break
                    
                    try:
                        title = item.find("title").text
                        link = item.find("link").text
                        pub_date = item.find("pubDate").text
                        source = item.find("source").text if item.find("source") is not None else "Google News"
                        
                        # Formatting relative time
                        try:
                            dt = parsedate_to_datetime(pub_date)
                            now = datetime.now(dt.tzinfo)
                            diff = now - dt
                            if diff.days > 0:
                                time_str = f"{diff.days}d ago"
                            elif diff.seconds > 3600:
                                time_str = f"{diff.seconds // 3600}h ago"
                            else:
                                time_str = f"{diff.seconds // 60}m ago"
                        except:
                            time_str = "Recently"

                        articles.append(NewsArticle(
                            title=title,
                            url=link,
                            source=source,
                            published_at=time_str
                        ))
                        count += 1
                    except Exception as parse_err:
                        print(f"Error parsing article: {parse_err}")
                        continue
        except Exception as e:
            print(f"News fetch error: {e}")
            # Don't fail the whole app, just return empty list
            pass
            
    return {"city": city, "articles": articles}


@app.get("/analytics")
async def get_analytics(city: str = "Hyderabad"):
    """
    Get historical AQI trends, future predictions, and AccuWeather insights.
    """
    import ml_engine
    import accuweather_client
    import ml_engine_lgbm

    print(f"Analytics requested for {city}")
    
    # 1. Get Prediction Seed
    live_aqi = 100 
    current_pm25 = 45.0 # Default fallback
    
    # 2. Fetch Live Data (Sensor Fusion + AccuWeather)
    accu_data = None
    async with httpx.AsyncClient() as client:
        try:
            coords = await fetch_coordinates(client, city)
            aq_data = await fetch_air_quality(client, coords["lat"], coords["lon"])
            
            # Map OpenWeather Index to AQI for seeding the model
            # Use calculated AQI directly
            live_aqi = aq_data["aqi_index"]
            if "pm2_5" in aq_data["components"]:
                current_pm25 = aq_data["components"]["pm2_5"]
            
            # ACCUWEATHER INTEGRATION
            try:
                print("Fetching AccuWeather data...")
                accu_full = await accuweather_client.fetch_accuweather_data(client, city)
                if accu_full:
                    accu_data = accu_full.get("current") 
            except Exception as e:
                print(f"AccuWeather fetch failed: {e}")

        except Exception as e:
             print(f"Live data fetch error: {e}")

    # 3. Generate ML Predictions (Prefer LightGBM)
    predictions = []
    model_source = "Random Forest (Fallback)"
    
    try:
        # Try LightGBM first
        pm25_preds = ml_engine_lgbm.predict_pm25_next_days(state="Telangana", city=city, current_pm25=current_pm25, days=4)
        # Convert PM2.5 to AQI (Approximate for display)
        # Ind-AQI sub-index for PM2.5: 
        # 0-30->0-50, 30-60->50-100, 60-90->100-200, 90-120->200-300, 120-250->300-400
        for p in pm25_preds:
            pm = p["predicted_pm25"]
            aqi = pm * 2 # Roughly 2x for simplistic conversion in moderate range
            if pm > 60: aqi = 100 + (pm - 60) * 3.3
            if pm > 90: aqi = 200 + (pm - 90) * 3.3
            if pm > 120: aqi = 300 + (pm - 120) * 0.7
            
            predictions.append({
                "date": p["date"],
                "predicted_aqi": int(aqi),
                "predicted_pm25": pm
            })
        model_source = "LightGBM (City-Aware)"
    except Exception as e:
        print(f"LightGBM failed, falling back to RF: {e}")
        predictions = ml_engine.predict_days(live_aqi, days=4)

    return {
        "city": city,
        "current_aqi_estimate": live_aqi,
        "forecast": predictions,
        "status": "generated",
        "model_source": model_source
    }

@app.get("/hotspots", response_model=List[FusedSensorSnapshot])
async def get_live_hotspots():
    """
    Returns live fused data for major Indian cities.
    """
    # Updated list of 7 major cities correctly
    cities = ["New Delhi", "Mumbai", "Hyderabad", "Bangalore", "Chennai", "Kolkata", "Ayodhya"]
    
    async with httpx.AsyncClient() as client:
        # 1. Geocode all cities in parallel
        coord_tasks = [fetch_coordinates(client, city) for city in cities]
        coords_results = await asyncio.gather(*coord_tasks, return_exceptions=True)
        
        valid_coords = []
        for res in coords_results:
            if not isinstance(res, Exception):
                valid_coords.append(res)
        
        # 2. Fetch Data for all cities in parallel
        # We need to replicate the fusion logic here efficiently
        fusion_tasks = []
        
        async def fetch_city_data(c):
            try:
                lat, lon = c["lat"], c["lon"]
                aq_data, w_data = await asyncio.gather(
                    fetch_air_quality(client, lat, lon),
                    fetch_weather(client, lat, lon),
                )
                ts = max(aq_data["dt"], w_data["dt"])
                dispersion = compute_dispersion_score(
                    aqi_index=aq_data["aqi_index"],
                    wind_speed=w_data["wind_speed"],
                    clouds=w_data["clouds"],
                )
                health_risk = aqi_to_category(aq_data["aqi_index"])
                insight = generate_agent_insight(health_risk, w_data["wind_speed"], aq_data["components"]["pm2_5"], aq_data["components"]["pm10"], aq_data["aqi_index"])
                
                # Append City Name to insight for context
                insight = f"{c['name']}: {insight}" 
                
                snapshot = FusedSensorSnapshot(
                    lat=lat,
                    lon=lon,
                    timestamp_utc=datetime.fromtimestamp(ts),
                    air_quality=AirQuality(
                        aqi_index=aq_data["aqi_index"],
                        aqi_category=health_risk,
                        components=PollutantComponents(**aq_data["components"]),
                    ),
                    weather=Weather(**{k: v for k, v in w_data.items() if k != "dt"}),
                    dispersion_score=dispersion,
                    health_risk_level=health_risk,
                    agent_insight=insight
                )
                return snapshot
            except Exception as e:
                print(f"Error fetching hotspot for {c['name']}: {e}")
                return None

        for c in valid_coords:
            fusion_tasks.append(fetch_city_data(c))
            
        snapshots = await asyncio.gather(*fusion_tasks)
        valid_snapshots = [s for s in snapshots if s is not None]

        # Log to cache
        if valid_snapshots:
            # We log the whole batch or individual items? Let's log brief summary
            await save_to_json_cache({
                "type": "hotspots_update",
                "count": len(valid_snapshots),
                "cities": [s.agent_insight.split(':')[0] for s in valid_snapshots], # extracted name from insight hack
                "data_sample": json.loads(valid_snapshots[0].json()) if valid_snapshots else None
            })

        return valid_snapshots

@app.get("/predict/pm25", response_model=List[PM25ForecastItem])
def predict_pm25_endpoint(
    state: str = Query(..., example="Telangana"),
    city: str = Query(..., example="Hyderabad"),
    current_pm25: float = Query(..., example=90.0),
    days: int = Query(3, ge=1, le=7),
):
    import ml_engine_lgbm
    return ml_engine_lgbm.predict_pm25_next_days(state, city, current_pm25, days)



@app.get("/explorer/history")
async def get_explorer_history(city: str = "Hyderabad"):
    """
    Aggregates historical data from local Excel files for the dashboard.
    Returns trends, monthly averages, and summary stats.
    """
    try:
        import pandas as pd
        import glob
        
        data_dir = "data"
        # Find all excel files matching the city (case insensitive)
        # We list all xlsx files and filter in python to be safe against case sensitivity
        all_files = glob.glob(f"{data_dir}/*.xlsx")
        files = [f for f in all_files if city.lower() in f.lower()]
        
        if not files:
            # Fallback for debugging: print what we found
            print(f"No files found for {city} in {data_dir}. Available: {all_files}")
            # Optional: Fallback to dummy data only if STRICTLY needed, or just return empty
            # files = glob.glob(f"{data_dir}/dummy_aqi.xlsx")
            
        if not files:
            return {"error": f"No historical data found for {city}"}

        dfs = []
        for f in files:
            try:
                df = pd.read_excel(f)
                dfs.append(df)
            except Exception as e:
                print(f"Error reading {f}: {e}")
                continue
        
        if not dfs:
            return {"error": "Could not read data files"}
            
        full_df = pd.concat(dfs, ignore_index=True)
        
        # Normalize columns
        # Map various possible names to standard keys
        col_map = {
            'Temp (degree C)': 'temp',
            'AT (degree C)': 'temp',
            'temperature': 'temp',
            'RH (%)': 'humidity',
            'humidity': 'humidity',
            'WS (m/s)': 'wind_speed',
            'wind_speed': 'wind_speed'
        }
        full_df = full_df.rename(columns=col_map)
        
        # Ensure Date column exists and is datetime
        date_col = None
        for col in full_df.columns:
            if "date" in col.lower():
                date_col = col
                break
        
        if not date_col:
            print(f"Columns found: {full_df.columns}")
            return {"error": "Date column missing in data"}
            
        full_df[date_col] = pd.to_datetime(full_df[date_col])
        full_df = full_df.sort_values(date_col)
        
        # 1. Summary Stats
        summary = {
            "total_records": int(len(full_df)),
            "avg_aqi": int(full_df['AQI'].mean()) if 'AQI' in full_df else 0,
            "avg_pm25": float(full_df['PM2.5'].mean()) if 'PM2.5' in full_df else 0,
            "max_aqi": int(full_df['AQI'].max()) if 'AQI' in full_df else 0
        }
        
        # 2. Trend Data (Daily)
        # Resample to daily if dense, or just take the records
        trend_df = full_df.copy()
        trend_df['date_str'] = trend_df[date_col].dt.strftime('%Y-%m-%d')
        trend_data = trend_df.to_dict(orient='records')
        # Clean keys for frontend
        clean_trend = []
        for item in trend_data:
            # map columns if they exist (handling variations simplistically)
            # EDA code showed: 'Temp (degree C)', 'RH (%)', 'WS (m/s)'
            row = {}
            row["date"] = item[date_col].strftime('%Y-%m-%d')
            row["aqi"] = item.get('AQI', 0)
            row["pm25"] = item.get('PM2.5', 0)
            
            # Weather metrics (using normalized names)
            row["temp"] = item.get('temp', 0)
            row["humidity"] = item.get('humidity', 0)
            row["wind_speed"] = item.get('wind_speed', 0)
            
            clean_trend.append(row)
            
        # 3. Monthly Distribution (Boxplot-ish stats)
        full_df['Month'] = full_df[date_col].dt.month_name().str[:3] # Jan, Feb...
        monthly_stats = []
        months_order = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        
        for month in months_order:
            m_df = full_df[full_df['Month'] == month]
            if not m_df.empty:
                monthly_stats.append({
                    "name": month,
                    "avg_pm25": float(m_df['PM2.5'].mean()),
                    "max_pm25": float(m_df['PM2.5'].max()),
                    "min_pm25": float(m_df['PM2.5'].min())
                })
        
        return {
            "city": city,
            "summary": summary,
            "trend": clean_trend,
            "monthly": monthly_stats
        }

    except Exception as e:
        print(f"Explorer error: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    import uvicorn
    print("Starting Sensor Fusion Agent on port 8100...")
    uvicorn.run(app, host="0.0.0.0", port=8100)

